// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "bootstrap"
import "jquery-easing"
import "sb-admin-2"
import "chart"
import "chart-area-demo"
import "chart-pie-demo"
